version: '3'
services:
  arangodb:
    image: 'arangodb:3.10'
    environment:
      ARANGO_ROOT_PASSWORD: root
    ports:
      - 8529:8529
    volumes:
      - arango-data:/var/lib/arangodb3
  postgres:
    image: 'postgres:15-alpine'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  arango-data:
  pgdata: