version: '3'
services:
  arangodb:
    image: 'arangodb:3.10'
    environment:
      ARANGO_ROOT_PASSWORD: root
    ports:
      - 8529:8529
    volumes:
      - arango-data:/var/lib/arangodb3
volumes:
  arango-data: